MBINCompiler.exe METADATA\REALITY\TABLES\BASEBUILDINGTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\COSTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\DAMAGETABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\DISCOVERYREWARDLOOKUPTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\EXPEDITIONEVENTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\EXPEDITIONREWARDTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\FRIGATETRAITTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\INVENTORYTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\LEGACYBASEBUILDINGTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\LEGACYITEMTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\MAINTENANCEGROUPSTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_DIALOG_GCALIENPUZZLETABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_DIALOG_GCALIENSPEECHTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_DIALOG_SPECIALISTPUZZLETABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_REALITY_GCPROCEDURALTECHNOLOGYTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_REALITY_GCPROCPRODUCTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_REALITY_GCSUBSTANCETABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_TESTREALITY_GCPRODUCTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_TESTREALITY_GCSUBSTANCETABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_TESTREALITY_GCTECHNOLOGYTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_U3REALITY_GCPRODUCTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_U3REALITY_GCSUBSTANCETABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\NMS_U3REALITY_GCTECHNOLOGYTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\PROCEDURALPRODUCTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\PROCEDURALTECHNOLOGYTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\PURCHASEABLEBUILDINGBLUEPRINTS.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\PURCHASEABLESPECIALS.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\REWARDDESTRUCTTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\REWARDTABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\TRADINGCLASSDATATABLE.MBIN
MBINCompiler.exe METADATA\REALITY\TABLES\TRADINGCOSTTABLE.MBIN

REM MBINCompiler.exe METADATA\REALITY\TABLES\
REM ren METADATA\REALITY\TABLES\


